using BannerlordTwitch.Helpers;
using BannerlordTwitch.Util;
using BLTAdoptAHero;
using BLTAdoptAHero.Util;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade;
using TaleWorlds.ObjectSystem;

int checks = 0;
void Check(bool condition, string message) { checks++; if (!condition) throw new Exception(message); }
void Throws(Action action, string message) { bool thrown = false; try { action(); } catch { thrown = true; } Check(thrown, message); }
CultureObject Culture(string id, string name, bool main = true) => new() { StringId = id, Name = name, IsMainCulture = main };
var empire = Culture("empire", "Empire");
var elves = Culture("elves", "Elven Kingdom");
var east = Culture("east", "Eastern Elves");
var hiddenCulture = Culture("smiths", "Smith Guild", false);
var noAssets = Culture("ghost", "Ghost Guild", false);
CampaignHelpers.AllCultures.AddRange(new[] { empire, elves, east, hiddenCulture, noAssets });
ItemObject Weapon(string id, EquipmentType type, CultureObject culture) => new() { StringId = id, Type = type, Culture = culture };
var bow = Weapon("elven_bow", EquipmentType.Bow, elves);
bow.PrimaryWeapon.IsMeleeWeapon = false; bow.PrimaryWeapon.IsRangedWeapon = true; bow.PrimaryWeapon.MissileDamage = 70;
var bow2 = Weapon("elven_bow_2", EquipmentType.Bow, elves);
var imperialBow = Weapon("empire_bow", EquipmentType.Bow, empire);
var guildCrossbow = Weapon("guild_crossbow", EquipmentType.Crossbow, hiddenCulture);
CampaignHelpers.AllItems.AddRange(new[] { bow, bow2, imperialBow, guildCrossbow });
var template = new CraftingTemplate { StringId = "custom_sword_template", WeaponDescriptions = new[] { new WeaponDescription { WeaponClass = WeaponClass.TwoHandedSword } }, BuildOrders = Enumerable.Range(0, 4).Select(i => new PieceData { PieceType = (CraftingPiece.PieceTypes)i, Order = i }).ToArray() };
foreach (var culture in new[] { empire, elves })
foreach (var tier in new[] { 2, 5 })
foreach (var slot in template.BuildOrders)
    template.Pieces.Add(new() { StringId = $"{culture.StringId}_{tier}_{slot.PieceType}", Culture = culture, PieceType = slot.PieceType, PieceTier = tier, Weight = tier / 10f });
CraftingTemplate.All.Add(template);
var hero = new Hero { Culture = elves, Class = new() { Weapons = new() { EquipmentType.Bow } } };
var campaign = BLTAdoptAHeroCampaignBehavior.Current;
var custom = BLTCustomItemsCampaignBehavior.Current;
var settings = GlobalForgeConfig.Config;
settings.Validate();
Check(settings.Price(ForgeQuality.Fine, false) == 750000, "quality prices");
settings.CultureSurcharge = 30;
Check(settings.Price(ForgeQuality.Fine, true) == 750030, "culture surcharge");
settings.CultureSurcharge = 0;
Check(ForgePolicy.Tokens("longsword \"Elven Kingdom\" swift fine").SequenceEqual(new[] { "longsword", "Elven Kingdom", "swift", "fine" }), "quoted parsing");
Throws(() => ForgePolicy.Tokens("bow \"elves"), "unclosed quote");
Check(!ForgePolicy.TryEnum("1", out ForgeStyle _), "numeric styles rejected");
Check(ForgePolicy.Contributions(100, 80, ForgeStyle.Swift, ForgeQuality.Fine, settings) == (20, 14), "swift fine contributions");
Check(ForgePolicy.Contributions(100, 80, ForgeStyle.Heavy, ForgeQuality.Masterwork, settings) == (45, 11), "heavy masterwork contributions");
Check(ForgePolicy.Contributions(10, 10, ForgeStyle.Swift, ForgeQuality.Standard, settings) == (9, 6), "symmetric midpoint rounding");
settings.CandidateBudget = 129; Throws(settings.Validate, "unbounded generation rejected"); settings.CandidateBudget = 64;
settings.StylePercent = double.NaN; Throws(settings.Validate, "NaN rejected"); settings.StylePercent = 5;
var badBonuses = settings.Copy();
badBonuses.MasterworkDamageBonus = 101; Throws(badBonuses.Validate, "excessive damage points rejected");
badBonuses = settings.Copy(); badBonuses.FineSpeedBonus = 4; Throws(badBonuses.Validate, "quality speed must progress");
Check(ForgePolicy.Contributions(90, 100, ForgeStyle.Balanced, ForgeQuality.Masterwork, settings) == (39, 15), "competitive Masterwork sword defaults");
Check(ForgePolicy.Contributions(90, 100, ForgeStyle.Balanced, ForgeQuality.Standard, settings) == (10, 5), "Standard custom bonuses");
var oldSettings = Newtonsoft.Json.JsonConvert.DeserializeObject<ForgeCommandSettings>("{\"StandardCost\":123456,\"MasterworkDamagePercent\":12}");
Check(oldSettings.StandardCost == 123456 && oldSettings.MasterworkDamagePercent == 12 && oldSettings.MasterworkDamageBonus == 30 && oldSettings.MasterworkSpeedBonus == 15, "existing command settings keep custom values and gain new default point bonuses");
var assets = ForgeAssets.Current;
Check(CampaignHelpers.MainCultures.All(assets.Cultures.Contains), "adoption/info culture parity");
Check(assets.Cultures.Contains(hiddenCulture) && !assets.Cultures.Contains(noAssets), "asset-backed non-main cultures");
Check(assets.ResolveCulture("ELVES", settings) == elves, "culture ID");
Check(assets.ResolveCulture("Elven Kingdom", settings) == elves, "culture name");
Check(assets.ResolveCulture("Elven", settings) == elves, "unique prefix");
Throws(() => assets.ResolveCulture("E", settings), "ambiguous prefix");
settings.CultureAliases["elf"] = "elves";
Check(assets.ResolveCulture("ELF", settings) == elves, "configured culture alias");
Check(assets.ResolveType("LONGSWORD", settings, out _) == EquipmentType.TwoHandedSword, "longsword alias");
Check(assets.ResolveType(template.StringId, settings, out var chosen) == EquipmentType.TwoHandedSword && chosen == template, "mod template IDs");
Throws(() => assets.ResolveType("arrows", settings, out _), "ammunition excluded");
var selected = assets.Generate(hero, EquipmentType.Bow, elves, ForgeStyle.Swift, settings, false);
Check(!selected.NativeCrafted && selected.Item.Culture == elves && !selected.Fallback, "existing culture weapon");
var seen = new HashSet<string>();
for (int i = 0; i < 40; i++) seen.Add(assets.Generate(hero, EquipmentType.Bow, elves, ForgeStyle.Balanced, settings, false).Item.StringId);
Check(seen.Count == 2, "existing weapons selected randomly within culture");
selected = assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Heavy, settings, false);
Check(selected.Fallback && selected.Description.Contains("fallback"), "culture fallback disclosed");
BLTAdoptAHeroModule.CommonConfig.RestrictedItemIds.Add(guildCrossbow.StringId);
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false), "restricted base item");
BLTAdoptAHeroModule.CommonConfig.RestrictedItemIds.Clear();
guildCrossbow.Compatible = false;
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false), "branch compatibility");
guildCrossbow.Compatible = true; guildCrossbow.Usable = false;
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, true), "random usability");
Check(assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false).Item == guildCrossbow, "explicit skill-ineligible weapon can be stored");
guildCrossbow.Usable = true;
int generated = Crafting.Generated, registered = MBObjectManager.Instance.Objects.Count;
selected = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Swift, settings, false);
Check(selected.NativeCrafted && !selected.Fallback, "native cultured design");
Check(Crafting.Generated - generated == settings.CandidateBudget && registered == MBObjectManager.Instance.Objects.Count, "bounded unregistered candidates");
Check(selected.Item.WeaponDesign.UsedPieces.All(p => p.CraftingPiece.Culture == elves), "culture-specific parts");
// Neutral crafting parts must still produce a culture-bearing item for the native save event.
var originalPartCultures = template.Pieces.Select(p => p.Culture).ToArray();
foreach (var part in template.Pieces) part.Culture = null;
var neutralDesign = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false);
Check(neutralDesign.Fallback && neutralDesign.Item.Culture == elves, "neutral design retains fallback disclosure and requested culture");
NativeForgeAdapter.PrepareIdentity(neutralDesign.Item);
int beforeNeutralEvent = CampaignEventDispatcher.Instance.Crafted;
NativeForgeAdapter.Register(neutralDesign.Item);
Check(CampaignEventDispatcher.Instance.Crafted == beforeNeutralEvent + 1, "neutral design survives native culture dereference and registration");
MBObjectManager.Instance.UnregisterObject(neutralDesign.Item);
var heroCultureDesign = assets.Generate(hero, EquipmentType.TwoHandedSword, null, ForgeStyle.Balanced, settings, false);
Check(heroCultureDesign.Item.Culture == hero.Culture, "neutral design without requested culture uses hero culture");
for (int i = 0; i < template.Pieces.Count; i++) template.Pieces[i].Culture = originalPartCultures[i];
Throws(() => NativeForgeAdapter.Register(new ItemObject()), "cultureless native registration rejected before event");
settings.TargetTier = 2;
selected = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false);
Check(selected.Item.Tierf < 4, "requested tier honored");
settings.TargetTier = 5;
foreach (var part in template.Pieces) part.IsHiddenOnDesigner = true;
Throws(() => assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false), "hidden parts excluded; no item fallback for broken template");
settings.AllowHiddenParts = true;
Check(assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false).NativeCrafted, "hidden part override");
settings.AllowHiddenParts = false;
foreach (var part in template.Pieces) part.IsHiddenOnDesigner = false;
var forge = new ForgeWeapon();
string reply = forge.Test(hero, "bow elves swift fine");
var item = campaign.GetCustomItems(hero).Single();
Check(reply.Contains("existing weapon design") && campaign.Gold == 9250000 && campaign.SpentGold == 750000, "forge cost and reply");
Check(item.Item.Culture == elves && item.ItemModifier.Damage == 20 && item.ItemModifier.Speed == 14, "style and quality modifiers");
Check(bow.PrimaryWeapon.SwingDamage == 100 && bow.PrimaryWeapon.SwingSpeed == 80, "shared base untouched");
Check(hero.BattleEquipment[EquipmentIndex.Weapon0].ItemModifier == item.ItemModifier, "eligible auto-equip");
Check(custom.GetForgeMetadata(item.ItemModifier).Quality == ForgeQuality.Fine, "forge metadata");
var reforge = new ReforgeWeapon();
reply = reforge.Test(hero, "#1 upgrade");
Check(reply.Contains("Masterwork") && item.ItemModifier.Damage == 35 && campaign.Gold == 9000000, "guaranteed quality upgrade");
custom.Enchant(item.ItemModifier, EnchantmentStat.Damage, 5, 0, 99, hero, 100);
custom.NameItem(item.ItemModifier, "My heirloom");
reply = reforge.Test(hero, "#1 heavy");
Check(item.ItemModifier.Damage == 50 && item.ItemModifier.Speed == 11 && custom.GetEnchantmentLevel(item.ItemModifier) == 1, "style replaces contributions and preserves enchantment");
reply = reforge.Test(hero, "#1 swift");
Check(item.ItemModifier.Damage == 40 && item.ItemModifier.Speed == 19, "reversal without accumulation");
Check(item.ItemModifier.Name.ToString() == "My heirloom" && campaign.GetCustomItems(hero).Count == 1, "identity/name/inventory preserved");
int gold = campaign.Gold;
reply = reforge.Test(hero, "#1 upgrade"); Check(reply.Contains("Already") && campaign.Gold == gold, "quality cap free");
reply = reforge.Test(hero, "#1 swift"); Check(reply.Contains("Already") && campaign.Gold == gold, "same style free");
settings.MasterworkDamageBonus += 2;
Check(reforge.Test(hero, "#1").Contains("Refresh current balance free"), "preview advertises free balance refresh");
reply = reforge.Test(hero, "#1 swift");
Check(campaign.Gold == gold && item.ItemModifier.Damage == 42 && item.ItemModifier.Speed == 19, "same-style balance refresh is free and preserves enchantment");
reforge.Test(hero, "#1 swift");
Check(campaign.Gold == gold && item.ItemModifier.Damage == 42, "refresh cannot stack bonuses");
settings.MasterworkDamageBonus -= 2;
reforge.Test(hero, "#1 swift");
Check(item.ItemModifier.Damage == 40 && campaign.Gold == gold, "refresh restores configured balance without accumulation");
Mission.Current = new(); Check(forge.Test(hero, "bow").Contains("mission") && campaign.Gold == gold, "mission guard"); Mission.Current = null;
hero.HeroState = Hero.CharacterStates.Prisoner; Check(reforge.Test(hero, "#1 heavy").Contains("imprisoned") && campaign.Gold == gold, "prisoner guard"); hero.HeroState = Hero.CharacterStates.Active;
campaign.Auction = true; Check(reforge.Test(hero, "#1 heavy").Contains("auction") && campaign.Gold == gold, "auction guard"); campaign.Auction = false;
campaign.FailCharge = true;
var oldMeta = custom.GetForgeMetadata(item.ItemModifier);
reply = reforge.Test(hero, "#1 heavy");
Check(campaign.Gold == gold && item.ItemModifier.Damage == 40 && custom.GetForgeMetadata(item.ItemModifier).Style == oldMeta.Style, "reforge rollback including metadata");
campaign.FailCharge = false;
campaign.FailAdd = true;
registered = MBObjectManager.Instance.Objects.Count;
reply = forge.Test(hero, "bow");
Check(campaign.Gold == gold && campaign.GetCustomItems(hero).Count == 1 && MBObjectManager.Instance.Objects.Count == registered, "forge rollback including registered modifier");
campaign.FailAdd = false;
BLTAdoptAHeroModule.CommonConfig.CustomItemLimit = 1;
Check(forge.Test(hero, "bow").Contains("full") && campaign.Gold == gold, "inventory cap free");
BLTAdoptAHeroModule.CommonConfig.CustomItemLimit = 10;
var legacy = new EquipmentElement(bow, custom.CreateWeaponModifier("Old {ITEMNAME}", 30, 8, 12, 2));
campaign.AddCustomItem(hero, legacy);
reforge.Test(hero, "#2 upgrade");
Check(legacy.ItemModifier.Damage == 55 && legacy.ItemModifier.Speed == 18 && legacy.ItemModifier.MissileSpeed == 12 && legacy.ItemModifier.StackCount == 2, "legacy bonus baseline protected");
Check(custom.GetForgeMetadata(legacy.ItemModifier).BaselineDamage == 30, "legacy metadata baseline");
var untouchedLegacy = new EquipmentElement(bow, custom.CreateWeaponModifier("Untouched legacy", 17, 3, 9, 4));
campaign.AddCustomItem(hero, untouchedLegacy);
var store = new Store();
custom.SyncData(store);
Campaign.Current.Custom = new();
store.IsLoading = true;
Campaign.Current.Custom.SyncData(store);
custom = BLTCustomItemsCampaignBehavior.Current;
Check(custom.GetForgeMetadata(item.ItemModifier).Style == ForgeStyle.Swift && custom.GetForgeMetadata(item.ItemModifier).Quality == ForgeQuality.Masterwork, "metadata save/reload");
Check(custom.GetEnchantmentLevel(item.ItemModifier) == 1 && item.ItemModifier.Name.ToString() == "My heirloom", "enchantment and rename save/reload");
Check(custom.GetForgeMetadata(untouchedLegacy.ItemModifier) == null && untouchedLegacy.ItemModifier.Damage == 17, "unmodified legacy loads without metadata");
// Simulate a pre-forge save by removing the additive field from the real JSON format.
var oldStore = new Store { Data = new(store.Data) };
var envelope = Newtonsoft.Json.Linq.JObject.Parse(string.Concat((string[])oldStore.Data["ModifierData"]));
var oldData = Newtonsoft.Json.Linq.JArray.Parse((string)envelope["Data"]);
foreach (var row in oldData) ((Newtonsoft.Json.Linq.JObject)row).Remove("Forge");
envelope["Data"] = oldData.ToString(Newtonsoft.Json.Formatting.None);
oldStore.Data["ModifierData"] = new[] { envelope.ToString(Newtonsoft.Json.Formatting.None) };
oldStore.IsLoading = true;
Campaign.Current.Custom = new();
Campaign.Current.Custom.SyncData(oldStore);
Check(BLTCustomItemsCampaignBehavior.Current.GetForgeMetadata(item.ItemModifier) == null && item.ItemModifier.Damage == 40, "pre-forge JSON saves preserve bonuses");
Check(BLTCustomItemsCampaignBehavior.Current.GetEnchantmentLevel(item.ItemModifier) == 1, "pre-forge enchantment history preserved");
Campaign.Current.Custom = new();
Campaign.Current.Custom.SyncData(store);
custom = BLTCustomItemsCampaignBehavior.Current;
hero.Class.Weapons = new() { EquipmentType.TwoHandedSword };
int crafted = CampaignEventDispatcher.Instance.Crafted;
reply = forge.Test(hero, "random");
Check(reply.Contains("native-crafted") && CampaignEventDispatcher.Instance.Crafted == crafted + 1, "random native forge and event registration");
var craftedItem = campaign.GetCustomItems(hero).Last();
Check(craftedItem.Item.StringId == craftedItem.Item.WeaponDesign.HashedCode && Guid.TryParse(craftedItem.Item.StringId, out _), "unique native identity");
Check(custom.GetForgeMetadata(craftedItem.ItemModifier).BaseItemId == craftedItem.Item.StringId, "registered provenance identity");
var recipient = new Hero { Culture = elves };
campaign.GetCustomItems(hero).Remove(item); campaign.AddCustomItem(recipient, item);
Check(custom.GetForgeMetadata(campaign.GetCustomItems(recipient).Single().ItemModifier).Quality == ForgeQuality.Masterwork, "ownership transfer retains metadata");
Check(reforge.Test(hero, "#99 heavy").Contains("Select"), "stale inventory index free");
// Random skips unusable types before any purchase and stays within the native budget.
hero.Class.Weapons = new() { EquipmentType.Crossbow, EquipmentType.Bow };
guildCrossbow.Usable = false;
for (int i = 0; i < 5; i++) Check(assets.GenerateRandom(hero, elves, ForgeStyle.Balanced, settings).type == EquipmentType.Bow, "random skips unusable class type");
guildCrossbow.Usable = true;
settings.TypeAliases["modblade"] = template.StringId;
Check(assets.ResolveType("modblade", settings, out chosen) == EquipmentType.TwoHandedSword && chosen == template, "aliases can target mod templates");
Check(assets.ResolveType("longsword", settings, out chosen) == EquipmentType.TwoHandedSword && chosen == null, "type aliases allow every compatible template");
var beforeCatalogue = ForgeAssets.Current;
Campaign.Current = new();
Check(!ReferenceEquals(beforeCatalogue, ForgeAssets.Current), "new campaign catalogue isolation");
ForgeAssets.Reset();
Check(!ReferenceEquals(beforeCatalogue, ForgeAssets.Current), "explicit catalogue reset");
// Real profile merge policy preserves custom names, disabled states and settings.
var defaultForge = new BannerlordTwitch.Command { Name = "forge", Handler = "ForgeWeapon", Enabled = false };
var defaultReforge = new BannerlordTwitch.Command { Name = "reforge", Handler = "ReforgeWeapon", Enabled = false };
var unrelated = new BannerlordTwitch.Command { Name = "balance", Handler = "BalanceCommand" };
var defaults = new[] { defaultForge, defaultReforge, unrelated };
var commands = new List<BannerlordTwitch.Command>();
Check(BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults) && commands.Count == 2, "add feature commands only");
Check(!BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults) && commands.Count == 2, "idempotent profile update");
var configured = new BannerlordTwitch.Command { Name = "blacksmith", Handler = "ForgeWeapon", Enabled = false, HandlerConfig = new object() };
commands = new() { configured };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0] == configured && !commands[0].Enabled && commands[0].Name == "blacksmith", "renamed disabled handler preserved");
commands = new() { new() { Name = "FORGE", Handler = "OtherHandler" } };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0].Handler == "OtherHandler", "command name collision preserved");
commands = new() { new() { Name = "privateforge", Handler = "OtherHandler", ID = defaultForge.ID } };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0].Name == "privateforge", "command ID collision preserved");
var legacyWeapon = new BannerlordTwitch.Command { Handler="SmithItem", Name="myweapon", Enabled=false,
    HandlerConfig=new Dictionary<string, object> { ["Type"]="Weapon", ["GoldCost"]=123456, ["CultureGoldCost"]=42, ["ItemPower"]=1.25 } };
var legacyId=legacyWeapon.ID;
var armorCommand=new BannerlordTwitch.Command { Handler="SmithItem", Name="smitharmor", HandlerConfig=new Dictionary<string, object> { ["Type"]="Armor" } };
var mountCommand=new BannerlordTwitch.Command { Handler="SmithItem", Name="buymount", HandlerConfig=new Dictionary<string, object> { ["Type"]="Mount" } };
var oldConfig=legacyWeapon.HandlerConfig;
Check(BannerlordTwitch.LegacyWeaponCommandMigration.Migrate(new[]{legacyWeapon,armorCommand,mountCommand}), "legacy weapon migration runs");
Check(legacyWeapon.Handler=="ForgeWeapon" && legacyWeapon.Name=="myweapon" && legacyWeapon.ID==legacyId && !legacyWeapon.Enabled, "migration preserves identity, name and disabled state");
Check(armorCommand.Handler=="SmithItem" && mountCommand.Handler=="SmithItem", "armour and mount commands remain legacy");
var migrated=(Dictionary<string,object>)legacyWeapon.HandlerConfig;
Check((int)migrated["StandardCost"]==123456 && (int)migrated["FineCost"]==373456 && (int)migrated["MasterworkCost"]==623456 && (int)migrated["CultureSurcharge"]==42, "migration carries purchase prices");
Check(ReferenceEquals(migrated["LegacySmithSettings"],oldConfig), "legacy power/name settings retained for reference");
Check(!BannerlordTwitch.LegacyWeaponCommandMigration.Migrate(new[]{legacyWeapon}), "weapon migration is idempotent");
var shared = new Dictionary<string,object> { ["StandardCost"]=987654, ["StylePercent"]=7.0 };
var fromShared = new BannerlordTwitch.Command { Handler="ForgeWeapon", HandlerConfig=new Dictionary<string,object> { ["UseGlobalSettings"]=true, ["StandardCost"]=1 } };
var fromCommand = new BannerlordTwitch.Command { Handler="ReforgeWeapon", HandlerConfig=new Dictionary<string,object> { ["UseGlobalSettings"]=false, ["UpgradeCost"]=123 } };
var emptyCommand = new BannerlordTwitch.Command { Handler="ReforgeWeapon" };
Check(BannerlordTwitch.LegacyWeaponCommandMigration.Localize(new[]{fromShared,fromCommand,emptyCommand,legacyWeapon},shared), "shared forging settings migrate to command settings");
Check(Convert.ToInt32(((Dictionary<string,object>)fromShared.HandlerConfig)["StandardCost"])==987654, "active shared price preserved on command");
Check(Convert.ToInt32(((Dictionary<string,object>)fromCommand.HandlerConfig)["UpgradeCost"])==123, "existing command-specific prices preserved");
Check(Convert.ToInt32(((Dictionary<string,object>)emptyCommand.HandlerConfig)["StandardCost"])==987654, "older commands without config inherit former shared values");
Check(Convert.ToInt32(((Dictionary<string,object>)legacyWeapon.HandlerConfig)["StandardCost"])==123456, "legacy weapon purchase price survives local migration");
Check(!((Dictionary<string,object>)fromShared.HandlerConfig).ContainsKey("UseGlobalSettings"), "obsolete shared switch removed");
Check(!BannerlordTwitch.LegacyWeaponCommandMigration.Localize(new[]{fromShared,fromCommand,emptyCommand,legacyWeapon},shared), "command-only migration idempotent");
Check(typeof(ForgeCommandSettings).GetProperty("UseGlobalSettings")==null, "command editor has no shared settings switch");
Check(new ForgeWeapon().HandlerConfigType==typeof(ForgeCommandSettings) && new ReforgeWeapon().HandlerConfigType==typeof(ReforgeCommandSettings), "both commands expose editable settings");
Check(typeof(ForgeSettings).GetProperties().Where(p=>p.CanWrite).All(p=>Attribute.IsDefined(p,typeof(System.ComponentModel.DisplayNameAttribute))), "all forge settings have readable editor labels");
// Exercise the actual equipcustom handler, including the invalid selection from the stream log.
var equip = new BLTAdoptAHero.Actions.EquipCustomItemAction();
var equipSettings = Activator.CreateInstance(equip.HandlerConfigType, true);
equip.HandlerConfigType.GetProperty("GoldCost").SetValue(equipSettings, 125);
var equipCampaign = BLTAdoptAHeroCampaignBehavior.Current;
var equipHero = new Hero { Class = new() { Weapons = new() { EquipmentType.OneHandedSword, EquipmentType.Bow, EquipmentType.OneHandedSword } } };
var forgedSword = new EquipmentElement(Weapon("custom_sword", EquipmentType.OneHandedSword, elves),
    BLTCustomItemsCampaignBehavior.Current.CreateWeaponModifier("Forged sword", 39, 15, 0, 0));
equipCampaign.AddCustomItem(equipHero, forgedSword);
var oldPolearm = new EquipmentElement(Weapon("old_polearm", EquipmentType.TwoHandedLance, elves));
equipHero.BattleEquipment[EquipmentIndex.Weapon0] = oldPolearm;
int equipGold = equipCampaign.Gold;
reply = equip.TestConfigured(equipHero, "1 slot2", equipSettings);
Check(reply.Contains("not found") && equipCampaign.Gold == equipGold, "unsupported slot argument fails without null dereference or charge");
reply = equip.TestConfigured(equipHero, "unknown name", equipSettings);
Check(reply.Contains("not found") && equipCampaign.Gold == equipGold, "missing name fails without charge");
reply = equip.TestConfigured(equipHero, "1", equipSettings);
Check(reply.Contains("2 slots") && equipHero.BattleEquipment[EquipmentIndex.Weapon0].Item == forgedSword.Item
    && equipHero.BattleEquipment[EquipmentIndex.Weapon2].ItemModifier == forgedSword.ItemModifier
    && equipCampaign.Gold == equipGold - 125, "class-compatible forged sword replaces wrong type and fills empty matching slot, charging once");
equipGold = equipCampaign.Gold;
equipHero.Class.Weapons = new() { EquipmentType.Bow };
reply = equip.TestConfigured(equipHero, "1", equipSettings);
Check(reply.Contains("Cannot equip OneHandedSword") && reply.Contains("Bow") && equipCampaign.Gold == equipGold, "unsupported class weapon fails free");
equipHero.Class = null;
reply = equip.TestConfigured(equipHero, "Forged sword", equipSettings);
Check(reply.Contains("2 slots") && equipCampaign.Gold == equipGold - 125, "classless hero can use matching loadout slots");
equipCampaign.GetCustomItems(equipHero).Add(default);
equipGold = equipCampaign.Gold;
Check(equip.TestConfigured(equipHero, "2", equipSettings).Contains("not found") && equipCampaign.Gold == equipGold, "empty inventory entry rejected without charge");
equipHero.Class = new() { Weapons = new() { EquipmentType.OneHandedSword } };
equipHero.BattleEquipment[EquipmentIndex.Weapon0] = oldPolearm;
equipCampaign.FailCharge = true;
equip.TestConfigured(equipHero, "1", equipSettings);
Check(equipHero.BattleEquipment[EquipmentIndex.Weapon0].Item == oldPolearm.Item && equipCampaign.Gold == equipGold, "equip charge failure restores prior equipment and gold");
equipCampaign.FailCharge = false;
// Preserve the pre-fix manual polearm compatibility while keeping handedness restrictions.
var pikeHero = new Hero { Class = new() { Weapons = new() { EquipmentType.TwoHandedGlaive } } };
var pikeWeapon = Weapon("forged_pike", EquipmentType.TwoHandedLance, elves);
pikeWeapon.PrimaryWeapon.WeaponClass = WeaponClass.TwoHandedPolearm;
var pikeElement = new EquipmentElement(pikeWeapon, forgedSword.ItemModifier);
equipCampaign.AddCustomItem(pikeHero, pikeElement);
reply = equip.TestConfigured(pikeHero, "1", equipSettings);
Check(reply.Contains("Equipped") && pikeHero.BattleEquipment[EquipmentIndex.Weapon0].Item == pikeWeapon, "forged pike fits swinging two-handed polearm class slot");
pikeWeapon.PrimaryWeapon.WeaponClass = WeaponClass.LowGripPolearm;
Check(equip.TestConfigured(pikeHero, "1", equipSettings).Contains("Equipped"), "low-grip polearm fits two-handed polearm slot");
pikeHero.Class.Weapons = new() { EquipmentType.OneHandedLance };
equipGold = equipCampaign.Gold;
Check(equip.TestConfigured(pikeHero, "1", equipSettings).Contains("Cannot equip") && equipCampaign.Gold == equipGold, "two-handed pike does not bypass one-handed class restriction");
pikeWeapon.PrimaryWeapon.WeaponClass = WeaponClass.OneHandedPolearm;
pikeWeapon.Type = EquipmentType.OneHandedGlaive;
Check(equip.TestConfigured(pikeHero, "1", equipSettings).Contains("Equipped"), "swinging one-handed polearm fits one-handed lance slot");
pikeWeapon.PrimaryWeapon.WeaponClass = WeaponClass.TwoHandedPolearm;
pikeWeapon.Name = "Two Handed Polearm";
pikeWeapon.AlternateModes.Add(new WeaponComponentData { WeaponClass = WeaponClass.OneHandedPolearm });
Check(equip.TestConfigured(pikeHero, "1", equipSettings).Contains("Equipped"), "two-handed named primary mode does not hide valid one-handed secondary mode");
pikeWeapon.AlternateModes.Clear();
reply = equip.TestConfigured(pikeHero, "1", equipSettings);
Check(reply.Contains("Cannot equip") && reply.Contains("native modes: TwoHandedPolearm"), "genuine two-handed-only weapon is rejected with its native modes");
pikeWeapon.PrimaryWeapon = null;
Check(equip.TestConfigured(pikeHero, "1", equipSettings).Contains("Cannot equip"), "missing weapon data fails safely for polearm slot");
int overlayCount = Log.OverlayReplies.Count;
reply = forge.Test(hero, "cultures");
Check(reply != null && reply.Contains("Elven Kingdom") && Log.OverlayReplies.Count == overlayCount, "short culture list follows normal reply route");
var manyCultures = Enumerable.Range(1, 40).Select(i => Culture($"mod_culture_{i}", $"Modded Culture {i}")).ToArray();
CampaignHelpers.AllCultures.AddRange(manyCultures);
ForgeAssets.Reset();
reply = forge.Test(hero, "cultures");
Check(reply == null && Log.OverlayReplies.Count == overlayCount + 1, "long culture list goes only to overlay, without chat pagination");
Check(Log.OverlayReplies.Last().user == "Viewer" && Log.OverlayReplies.Last().message.Contains("mod_culture_1")
    && Log.OverlayReplies.Last().message.Contains("mod_culture_40"), "overlay receives complete untruncated culture list and viewer name");
foreach (var culture in manyCultures) CampaignHelpers.AllCultures.Remove(culture);
ForgeAssets.Reset();
var forgeGuide = new RecordingDocumentation();
var forgeGuideSettings = new ForgeCommandSettings { StandardCost = 123456, MasterworkDamageBonus = 33 };
forgeGuideSettings.GenerateDocumentation(forgeGuide);
string forgeHelp = string.Join(" ", forgeGuide.Values);
Check(forgeHelp.Contains("!forge &lt;type&gt; [culture] [style] [quality]") && forgeHelp.Contains("!forge OneHandedLance gondor balanced masterwork"), "forge Neo subsection contains escaped syntax and copyable culture example");
Check(forgeHelp.Contains(123456.ToString("N0")) && forgeHelp.Contains("+33 damage points"), "generated forge guide uses configured prices and bonuses");
Check(forgeHelp.Contains("!forge random") && forgeHelp.Contains("!forge cultures") && forgeHelp.Contains("!equipcustom 6"), "forge guide explains discovery, random forging and equipping");
var reforgeGuide = new RecordingDocumentation();
new ReforgeCommandSettings { UpgradeCost = 123456 }.GenerateDocumentation(reforgeGuide);
Check(string.Join(" ", reforgeGuide.Values).Contains(123456.ToString("N0")) && !string.Join(" ", reforgeGuide.Values).Contains("<strong>Forge a custom weapon"), "reforge has its own subsection and configured price");
Console.WriteLine($"PASS: {checks} forge integration checks (engine stubs; not real-game verification).");
