using BannerlordTwitch.Helpers;
using BannerlordTwitch.Util;
using BLTAdoptAHero;
using BLTAdoptAHero.Util;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.MountAndBlade;
using TaleWorlds.ObjectSystem;

int checks = 0;
void Check(bool condition, string message) { checks++; if (!condition) throw new Exception(message); }
void Throws(Action action, string message) { bool thrown = false; try { action(); } catch { thrown = true; } Check(thrown, message); }
CultureObject Culture(string id, string name, bool main = true) => new() { StringId = id, Name = name, IsMainCulture = main };
var empire = Culture("empire", "Empire");
var elves = Culture("elves", "Elven Kingdom");
var east = Culture("east", "Eastern Elves");
var hiddenCulture = Culture("smiths", "Smith Guild", false);
var noAssets = Culture("ghost", "Ghost Guild", false);
CampaignHelpers.AllCultures.AddRange(new[] { empire, elves, east, hiddenCulture, noAssets });
ItemObject Weapon(string id, EquipmentType type, CultureObject culture) => new() { StringId = id, Type = type, Culture = culture };
var bow = Weapon("elven_bow", EquipmentType.Bow, elves);
bow.PrimaryWeapon.IsMeleeWeapon = false; bow.PrimaryWeapon.IsRangedWeapon = true; bow.PrimaryWeapon.MissileDamage = 70;
var bow2 = Weapon("elven_bow_2", EquipmentType.Bow, elves);
var imperialBow = Weapon("empire_bow", EquipmentType.Bow, empire);
var guildCrossbow = Weapon("guild_crossbow", EquipmentType.Crossbow, hiddenCulture);
CampaignHelpers.AllItems.AddRange(new[] { bow, bow2, imperialBow, guildCrossbow });
var template = new CraftingTemplate { StringId = "custom_sword_template", WeaponDescriptions = new[] { new WeaponDescription { WeaponClass = WeaponClass.TwoHandedSword } }, BuildOrders = Enumerable.Range(0, 4).Select(i => new PieceData { PieceType = (CraftingPiece.PieceTypes)i, Order = i }).ToArray() };
foreach (var culture in new[] { empire, elves })
foreach (var tier in new[] { 2, 5 })
foreach (var slot in template.BuildOrders)
    template.Pieces.Add(new() { StringId = $"{culture.StringId}_{tier}_{slot.PieceType}", Culture = culture, PieceType = slot.PieceType, PieceTier = tier, Weight = tier / 10f });
CraftingTemplate.All.Add(template);
var hero = new Hero { Culture = elves, Class = new() { Weapons = new() { EquipmentType.Bow } } };
var campaign = BLTAdoptAHeroCampaignBehavior.Current;
var custom = BLTCustomItemsCampaignBehavior.Current;
var settings = GlobalForgeConfig.Config;
settings.Validate();
Check(settings.Price(ForgeQuality.Fine, false) == 750000, "quality prices");
settings.CultureSurcharge = 30;
Check(settings.Price(ForgeQuality.Fine, true) == 750030, "culture surcharge");
settings.CultureSurcharge = 0;
Check(ForgePolicy.Tokens("longsword \"Elven Kingdom\" swift fine").SequenceEqual(new[] { "longsword", "Elven Kingdom", "swift", "fine" }), "quoted parsing");
Throws(() => ForgePolicy.Tokens("bow \"elves"), "unclosed quote");
Check(!ForgePolicy.TryEnum("1", out ForgeStyle _), "numeric styles rejected");
Check(ForgePolicy.Contributions(100, 80, ForgeStyle.Swift, ForgeQuality.Fine, settings) == (0, 4), "swift fine contributions");
Check(ForgePolicy.Contributions(100, 80, ForgeStyle.Heavy, ForgeQuality.Masterwork, settings) == (15, -4), "heavy masterwork contributions");
Check(ForgePolicy.Contributions(10, 10, ForgeStyle.Swift, ForgeQuality.Standard, settings) == (-1, 1), "symmetric midpoint rounding");
settings.CandidateBudget = 129; Throws(settings.Validate, "unbounded generation rejected"); settings.CandidateBudget = 64;
settings.StylePercent = double.NaN; Throws(settings.Validate, "NaN rejected"); settings.StylePercent = 5;
var assets = ForgeAssets.Current;
Check(CampaignHelpers.MainCultures.All(assets.Cultures.Contains), "adoption/info culture parity");
Check(assets.Cultures.Contains(hiddenCulture) && !assets.Cultures.Contains(noAssets), "asset-backed non-main cultures");
Check(assets.ResolveCulture("ELVES", settings) == elves, "culture ID");
Check(assets.ResolveCulture("Elven Kingdom", settings) == elves, "culture name");
Check(assets.ResolveCulture("Elven", settings) == elves, "unique prefix");
Throws(() => assets.ResolveCulture("E", settings), "ambiguous prefix");
settings.CultureAliases["elf"] = "elves";
Check(assets.ResolveCulture("ELF", settings) == elves, "configured culture alias");
Check(assets.ResolveType("LONGSWORD", settings, out _) == EquipmentType.TwoHandedSword, "longsword alias");
Check(assets.ResolveType(template.StringId, settings, out var chosen) == EquipmentType.TwoHandedSword && chosen == template, "mod template IDs");
Throws(() => assets.ResolveType("arrows", settings, out _), "ammunition excluded");
var selected = assets.Generate(hero, EquipmentType.Bow, elves, ForgeStyle.Swift, settings, false);
Check(!selected.NativeCrafted && selected.Item.Culture == elves && !selected.Fallback, "existing culture weapon");
var seen = new HashSet<string>();
for (int i = 0; i < 40; i++) seen.Add(assets.Generate(hero, EquipmentType.Bow, elves, ForgeStyle.Balanced, settings, false).Item.StringId);
Check(seen.Count == 2, "existing weapons selected randomly within culture");
selected = assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Heavy, settings, false);
Check(selected.Fallback && selected.Description.Contains("fallback"), "culture fallback disclosed");
BLTAdoptAHeroModule.CommonConfig.RestrictedItemIds.Add(guildCrossbow.StringId);
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false), "restricted base item");
BLTAdoptAHeroModule.CommonConfig.RestrictedItemIds.Clear();
guildCrossbow.Compatible = false;
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false), "branch compatibility");
guildCrossbow.Compatible = true; guildCrossbow.Usable = false;
Throws(() => assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, true), "random usability");
Check(assets.Generate(hero, EquipmentType.Crossbow, empire, ForgeStyle.Balanced, settings, false).Item == guildCrossbow, "explicit skill-ineligible weapon can be stored");
guildCrossbow.Usable = true;
int generated = Crafting.Generated, registered = MBObjectManager.Instance.Objects.Count;
selected = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Swift, settings, false);
Check(selected.NativeCrafted && !selected.Fallback, "native cultured design");
Check(Crafting.Generated - generated == settings.CandidateBudget && registered == MBObjectManager.Instance.Objects.Count, "bounded unregistered candidates");
Check(selected.Item.WeaponDesign.UsedPieces.All(p => p.CraftingPiece.Culture == elves), "culture-specific parts");
// Neutral crafting parts must still produce a culture-bearing item for the native save event.
var originalPartCultures = template.Pieces.Select(p => p.Culture).ToArray();
foreach (var part in template.Pieces) part.Culture = null;
var neutralDesign = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false);
Check(neutralDesign.Fallback && neutralDesign.Item.Culture == elves, "neutral design retains fallback disclosure and requested culture");
NativeForgeAdapter.PrepareIdentity(neutralDesign.Item);
int beforeNeutralEvent = CampaignEventDispatcher.Instance.Crafted;
NativeForgeAdapter.Register(neutralDesign.Item);
Check(CampaignEventDispatcher.Instance.Crafted == beforeNeutralEvent + 1, "neutral design survives native culture dereference and registration");
MBObjectManager.Instance.UnregisterObject(neutralDesign.Item);
var heroCultureDesign = assets.Generate(hero, EquipmentType.TwoHandedSword, null, ForgeStyle.Balanced, settings, false);
Check(heroCultureDesign.Item.Culture == hero.Culture, "neutral design without requested culture uses hero culture");
for (int i = 0; i < template.Pieces.Count; i++) template.Pieces[i].Culture = originalPartCultures[i];
Throws(() => NativeForgeAdapter.Register(new ItemObject()), "cultureless native registration rejected before event");
settings.TargetTier = 2;
selected = assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false);
Check(selected.Item.Tierf < 4, "requested tier honored");
settings.TargetTier = 5;
foreach (var part in template.Pieces) part.IsHiddenOnDesigner = true;
Throws(() => assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false), "hidden parts excluded; no item fallback for broken template");
settings.AllowHiddenParts = true;
Check(assets.Generate(hero, EquipmentType.TwoHandedSword, elves, ForgeStyle.Balanced, settings, false).NativeCrafted, "hidden part override");
settings.AllowHiddenParts = false;
foreach (var part in template.Pieces) part.IsHiddenOnDesigner = false;
var forge = new ForgeWeapon();
string reply = forge.Test(hero, "bow elves swift fine");
var item = campaign.GetCustomItems(hero).Single();
Check(reply.Contains("existing weapon design") && campaign.Gold == 9250000 && campaign.SpentGold == 750000, "forge cost and reply");
Check(item.Item.Culture == elves && item.ItemModifier.Damage == 0 && item.ItemModifier.Speed == 4, "style and quality modifiers");
Check(bow.PrimaryWeapon.SwingDamage == 100 && bow.PrimaryWeapon.SwingSpeed == 80, "shared base untouched");
Check(hero.BattleEquipment[EquipmentIndex.Weapon0].ItemModifier == item.ItemModifier, "eligible auto-equip");
Check(custom.GetForgeMetadata(item.ItemModifier).Quality == ForgeQuality.Fine, "forge metadata");
var reforge = new ReforgeWeapon();
reply = reforge.Test(hero, "#1 upgrade");
Check(reply.Contains("Masterwork") && item.ItemModifier.Damage == 5 && campaign.Gold == 9000000, "guaranteed quality upgrade");
custom.Enchant(item.ItemModifier, EnchantmentStat.Damage, 5, 0, 99, hero, 100);
custom.NameItem(item.ItemModifier, "My heirloom");
reply = reforge.Test(hero, "#1 heavy");
Check(item.ItemModifier.Damage == 20 && item.ItemModifier.Speed == -4 && custom.GetEnchantmentLevel(item.ItemModifier) == 1, "style replaces contributions and preserves enchantment");
reply = reforge.Test(hero, "#1 swift");
Check(item.ItemModifier.Damage == 10 && item.ItemModifier.Speed == 4, "reversal without accumulation");
Check(item.ItemModifier.Name.ToString() == "My heirloom" && campaign.GetCustomItems(hero).Count == 1, "identity/name/inventory preserved");
int gold = campaign.Gold;
reply = reforge.Test(hero, "#1 upgrade"); Check(reply.Contains("Already") && campaign.Gold == gold, "quality cap free");
reply = reforge.Test(hero, "#1 swift"); Check(reply.Contains("Already") && campaign.Gold == gold, "same style free");
Mission.Current = new(); Check(forge.Test(hero, "bow").Contains("mission") && campaign.Gold == gold, "mission guard"); Mission.Current = null;
hero.HeroState = Hero.CharacterStates.Prisoner; Check(reforge.Test(hero, "#1 heavy").Contains("imprisoned") && campaign.Gold == gold, "prisoner guard"); hero.HeroState = Hero.CharacterStates.Active;
campaign.Auction = true; Check(reforge.Test(hero, "#1 heavy").Contains("auction") && campaign.Gold == gold, "auction guard"); campaign.Auction = false;
campaign.FailCharge = true;
var oldMeta = custom.GetForgeMetadata(item.ItemModifier);
reply = reforge.Test(hero, "#1 heavy");
Check(campaign.Gold == gold && item.ItemModifier.Damage == 10 && custom.GetForgeMetadata(item.ItemModifier).Style == oldMeta.Style, "reforge rollback including metadata");
campaign.FailCharge = false;
campaign.FailAdd = true;
registered = MBObjectManager.Instance.Objects.Count;
reply = forge.Test(hero, "bow");
Check(campaign.Gold == gold && campaign.GetCustomItems(hero).Count == 1 && MBObjectManager.Instance.Objects.Count == registered, "forge rollback including registered modifier");
campaign.FailAdd = false;
BLTAdoptAHeroModule.CommonConfig.CustomItemLimit = 1;
Check(forge.Test(hero, "bow").Contains("full") && campaign.Gold == gold, "inventory cap free");
BLTAdoptAHeroModule.CommonConfig.CustomItemLimit = 10;
var legacy = new EquipmentElement(bow, custom.CreateWeaponModifier("Old {ITEMNAME}", 30, 8, 12, 2));
campaign.AddCustomItem(hero, legacy);
reforge.Test(hero, "#2 upgrade");
Check(legacy.ItemModifier.Damage == 35 && legacy.ItemModifier.Speed == 8 && legacy.ItemModifier.MissileSpeed == 12 && legacy.ItemModifier.StackCount == 2, "legacy bonus baseline protected");
Check(custom.GetForgeMetadata(legacy.ItemModifier).BaselineDamage == 30, "legacy metadata baseline");
var untouchedLegacy = new EquipmentElement(bow, custom.CreateWeaponModifier("Untouched legacy", 17, 3, 9, 4));
campaign.AddCustomItem(hero, untouchedLegacy);
var store = new Store();
custom.SyncData(store);
Campaign.Current.Custom = new();
store.IsLoading = true;
Campaign.Current.Custom.SyncData(store);
custom = BLTCustomItemsCampaignBehavior.Current;
Check(custom.GetForgeMetadata(item.ItemModifier).Style == ForgeStyle.Swift && custom.GetForgeMetadata(item.ItemModifier).Quality == ForgeQuality.Masterwork, "metadata save/reload");
Check(custom.GetEnchantmentLevel(item.ItemModifier) == 1 && item.ItemModifier.Name.ToString() == "My heirloom", "enchantment and rename save/reload");
Check(custom.GetForgeMetadata(untouchedLegacy.ItemModifier) == null && untouchedLegacy.ItemModifier.Damage == 17, "unmodified legacy loads without metadata");
// Simulate a pre-forge save by removing the additive field from the real JSON format.
var oldStore = new Store { Data = new(store.Data) };
var envelope = Newtonsoft.Json.Linq.JObject.Parse(string.Concat((string[])oldStore.Data["ModifierData"]));
var oldData = Newtonsoft.Json.Linq.JArray.Parse((string)envelope["Data"]);
foreach (var row in oldData) ((Newtonsoft.Json.Linq.JObject)row).Remove("Forge");
envelope["Data"] = oldData.ToString(Newtonsoft.Json.Formatting.None);
oldStore.Data["ModifierData"] = new[] { envelope.ToString(Newtonsoft.Json.Formatting.None) };
oldStore.IsLoading = true;
Campaign.Current.Custom = new();
Campaign.Current.Custom.SyncData(oldStore);
Check(BLTCustomItemsCampaignBehavior.Current.GetForgeMetadata(item.ItemModifier) == null && item.ItemModifier.Damage == 10, "pre-forge JSON saves preserve bonuses");
Check(BLTCustomItemsCampaignBehavior.Current.GetEnchantmentLevel(item.ItemModifier) == 1, "pre-forge enchantment history preserved");
Campaign.Current.Custom = new();
Campaign.Current.Custom.SyncData(store);
custom = BLTCustomItemsCampaignBehavior.Current;
hero.Class.Weapons = new() { EquipmentType.TwoHandedSword };
int crafted = CampaignEventDispatcher.Instance.Crafted;
reply = forge.Test(hero, "random");
Check(reply.Contains("native-crafted") && CampaignEventDispatcher.Instance.Crafted == crafted + 1, "random native forge and event registration");
var craftedItem = campaign.GetCustomItems(hero).Last();
Check(craftedItem.Item.StringId == craftedItem.Item.WeaponDesign.HashedCode && Guid.TryParse(craftedItem.Item.StringId, out _), "unique native identity");
Check(custom.GetForgeMetadata(craftedItem.ItemModifier).BaseItemId == craftedItem.Item.StringId, "registered provenance identity");
var recipient = new Hero { Culture = elves };
campaign.GetCustomItems(hero).Remove(item); campaign.AddCustomItem(recipient, item);
Check(custom.GetForgeMetadata(campaign.GetCustomItems(recipient).Single().ItemModifier).Quality == ForgeQuality.Masterwork, "ownership transfer retains metadata");
Check(reforge.Test(hero, "#99 heavy").Contains("Select"), "stale inventory index free");
// Random skips unusable types before any purchase and stays within the native budget.
hero.Class.Weapons = new() { EquipmentType.Crossbow, EquipmentType.Bow };
guildCrossbow.Usable = false;
for (int i = 0; i < 5; i++) Check(assets.GenerateRandom(hero, elves, ForgeStyle.Balanced, settings).type == EquipmentType.Bow, "random skips unusable class type");
guildCrossbow.Usable = true;
settings.TypeAliases["modblade"] = template.StringId;
Check(assets.ResolveType("modblade", settings, out chosen) == EquipmentType.TwoHandedSword && chosen == template, "aliases can target mod templates");
Check(assets.ResolveType("longsword", settings, out chosen) == EquipmentType.TwoHandedSword && chosen == null, "type aliases allow every compatible template");
var beforeCatalogue = ForgeAssets.Current;
Campaign.Current = new();
Check(!ReferenceEquals(beforeCatalogue, ForgeAssets.Current), "new campaign catalogue isolation");
ForgeAssets.Reset();
Check(!ReferenceEquals(beforeCatalogue, ForgeAssets.Current), "explicit catalogue reset");
// Real profile merge policy preserves custom names, disabled states and settings.
var defaultForge = new BannerlordTwitch.Command { Name = "forge", Handler = "ForgeWeapon", Enabled = false };
var defaultReforge = new BannerlordTwitch.Command { Name = "reforge", Handler = "ReforgeWeapon", Enabled = false };
var unrelated = new BannerlordTwitch.Command { Name = "balance", Handler = "BalanceCommand" };
var defaults = new[] { defaultForge, defaultReforge, unrelated };
var commands = new List<BannerlordTwitch.Command>();
Check(BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults) && commands.Count == 2, "add feature commands only");
Check(!BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults) && commands.Count == 2, "idempotent profile update");
var configured = new BannerlordTwitch.Command { Name = "blacksmith", Handler = "ForgeWeapon", Enabled = false, HandlerConfig = new object() };
commands = new() { configured };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0] == configured && !commands[0].Enabled && commands[0].Name == "blacksmith", "renamed disabled handler preserved");
commands = new() { new() { Name = "FORGE", Handler = "OtherHandler" } };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0].Handler == "OtherHandler", "command name collision preserved");
commands = new() { new() { Name = "privateforge", Handler = "OtherHandler", ID = defaultForge.ID } };
BannerlordTwitch.ForgeCommandDefaults.AddMissing(commands, defaults);
Check(commands.Count == 2 && commands[0].Name == "privateforge", "command ID collision preserved");
var legacyWeapon = new BannerlordTwitch.Command { Handler="SmithItem", Name="myweapon", Enabled=false,
    HandlerConfig=new Dictionary<string, object> { ["Type"]="Weapon", ["GoldCost"]=123456, ["CultureGoldCost"]=42, ["ItemPower"]=1.25 } };
var legacyId=legacyWeapon.ID;
var armorCommand=new BannerlordTwitch.Command { Handler="SmithItem", Name="smitharmor", HandlerConfig=new Dictionary<string, object> { ["Type"]="Armor" } };
var mountCommand=new BannerlordTwitch.Command { Handler="SmithItem", Name="buymount", HandlerConfig=new Dictionary<string, object> { ["Type"]="Mount" } };
var oldConfig=legacyWeapon.HandlerConfig;
Check(BannerlordTwitch.LegacyWeaponCommandMigration.Migrate(new[]{legacyWeapon,armorCommand,mountCommand}), "legacy weapon migration runs");
Check(legacyWeapon.Handler=="ForgeWeapon" && legacyWeapon.Name=="myweapon" && legacyWeapon.ID==legacyId && !legacyWeapon.Enabled, "migration preserves identity, name and disabled state");
Check(armorCommand.Handler=="SmithItem" && mountCommand.Handler=="SmithItem", "armour and mount commands remain legacy");
var migrated=(Dictionary<string,object>)legacyWeapon.HandlerConfig;
Check((int)migrated["StandardCost"]==123456 && (int)migrated["FineCost"]==373456 && (int)migrated["MasterworkCost"]==623456 && (int)migrated["CultureSurcharge"]==42, "migration carries purchase prices");
Check(ReferenceEquals(migrated["LegacySmithSettings"],oldConfig), "legacy power/name settings retained for reference");
Check(!BannerlordTwitch.LegacyWeaponCommandMigration.Migrate(new[]{legacyWeapon}), "weapon migration is idempotent");
var shared = new Dictionary<string,object> { ["StandardCost"]=987654, ["StylePercent"]=7.0 };
var fromShared = new BannerlordTwitch.Command { Handler="ForgeWeapon", HandlerConfig=new Dictionary<string,object> { ["UseGlobalSettings"]=true, ["StandardCost"]=1 } };
var fromCommand = new BannerlordTwitch.Command { Handler="ReforgeWeapon", HandlerConfig=new Dictionary<string,object> { ["UseGlobalSettings"]=false, ["UpgradeCost"]=123 } };
var emptyCommand = new BannerlordTwitch.Command { Handler="ReforgeWeapon" };
Check(BannerlordTwitch.LegacyWeaponCommandMigration.Localize(new[]{fromShared,fromCommand,emptyCommand,legacyWeapon},shared), "shared forging settings migrate to command settings");
Check(Convert.ToInt32(((Dictionary<string,object>)fromShared.HandlerConfig)["StandardCost"])==987654, "active shared price preserved on command");
Check(Convert.ToInt32(((Dictionary<string,object>)fromCommand.HandlerConfig)["UpgradeCost"])==123, "existing command-specific prices preserved");
Check(Convert.ToInt32(((Dictionary<string,object>)emptyCommand.HandlerConfig)["StandardCost"])==987654, "older commands without config inherit former shared values");
Check(Convert.ToInt32(((Dictionary<string,object>)legacyWeapon.HandlerConfig)["StandardCost"])==123456, "legacy weapon purchase price survives local migration");
Check(!((Dictionary<string,object>)fromShared.HandlerConfig).ContainsKey("UseGlobalSettings"), "obsolete shared switch removed");
Check(!BannerlordTwitch.LegacyWeaponCommandMigration.Localize(new[]{fromShared,fromCommand,emptyCommand,legacyWeapon},shared), "command-only migration idempotent");
Check(typeof(ForgeCommandSettings).GetProperty("UseGlobalSettings")==null, "command editor has no shared settings switch");
Check(new ForgeWeapon().HandlerConfigType==typeof(ForgeCommandSettings) && new ReforgeWeapon().HandlerConfigType==typeof(ForgeCommandSettings), "both commands expose editable settings");
Check(typeof(ForgeSettings).GetProperties().Where(p=>p.CanWrite).All(p=>Attribute.IsDefined(p,typeof(System.ComponentModel.DisplayNameAttribute))), "all forge settings have readable editor labels");
Console.WriteLine($"PASS: {checks} forge integration checks (engine stubs; not real-game verification).");
