<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="YamlDotNet">
      <HintPath>..\packages\YamlDotNet.15.3.0\lib\net8.0\YamlDotNet.dll</HintPath>
    </Reference>
    <Compile Include="..\BannerlordTwitch\Settings\ConfigurationVersioning.cs" Link="ConfigurationVersioning.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\SimGoldPolicy.cs" Link="SimGoldPolicy.cs" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\packages\Newtonsoft.Json.13.0.3\lib\net6.0\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Compile Include="..\BLTAdoptAHero\Util\EnchantmentPolicy.cs" Link="EnchantmentPolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\BattleBalancePolicy.cs" Link="BattleBalancePolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\PrestigePolicy.cs" Link="PrestigePolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\CycleSafeGraph.cs" Link="CycleSafeGraph.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\SmartTroopPolicy.cs" Link="SmartTroopPolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\AmmoReport.cs" Link="AmmoReport.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\CampaignMapGeometry.cs" Link="CampaignMapGeometry.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\StreamObjectivePolicy.cs" Link="StreamObjectivePolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\CursedArtifactPolicy.cs" Link="CursedArtifactPolicy.cs" />
    <Compile Include="..\BLTAdoptAHero\Util\RandomEventPolicy.cs" Link="RandomEventPolicy.cs" />
  </ItemGroup>
</Project>
